version: "3"
services:
  glassfish:
    image: travlendar_akm_glassfish
    ports:
     - "127.0.0.1:8080:8080"
    links:
     - mysql:mysql
    depends_on:
     - mysql
    environment:
      MYSQL_IP: mysql
    cap_add:
     - NET_ADMIN
  mysql:
    image: travlendar_akm_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: minorin
