version: "3"
services:
  endpoint:
    image: travlendar_endpoint
    ports:
     - "127.0.0.1:5000:8000"
    links:
     - rethinkdb_user:rethinkdb_user
     - optimalroute:optimalroute
    environment:
     - RETHINKDB_IP=rethinkdb_user
     - OPTIMALROUTE_IP=optimalroute
     - OPTIMALROUTE_PORT=6000
    depends_on:
     - rethinkdb_user
     - optimalroute
  rethinkdb_user:
    image: rethinkdb
    volumes:
     - /opt/rethinkdb_user:/data
  valhalla:
    image: valhalla_server_milan
  optimalroute:
    image: travlendar_optimalroute
    links:
     - valhalla:valhalla
    environment:
     - VALHALLA_IP=valhalla
    depends_on:
     - valhalla
  webinterface:
    image: travlendar_webinterface
    ports:
     - "127.0.0.1:80:80"
  rethinkdb_data:
    image: rethinkdb
    volumes:
     - /opt/rethinkdb_data:/data
  scraper:
    image: travlendar_scraper
    links:
     - rethinkdb_data:rethinkdb_data
    environment:
     - RETHINKDB_IP=rethinkdb_data
    depends_on:
     - rethinkdb_data
